### PR TITLE
feat(build): Add autoprefixer 

### LINKED ISSUE #3: Include autoprefixer in the build task
Should be placed somewhere here: https://github.com/caroso1222/ng-lib-schematics/blob/master/src/lib-standalone/files/lib/__path__/build-tools/build-scss-task.js#L12

### PR DESCRIPTION
**Pull request by NetanelBasal**
Closes #3

### CODE REVIEW

**Comment by caroso1222** [comment]
This is awesome, thank you for your contribution! :D

**Comment by NetanelBasal** [comment]
You are welcome :) Don't forget to release the version.

**Comment by NetanelBasal** [comment]
It would be great to add to the Features section:
- SASS and [autoprefixer](https://github.com/postcss/autoprefixer) support.

**Comment by caroso1222** [comment]
Thanks man!

1. Yeah definitely, I'll release 0.3.0 tomorrow after work for sure.
2. Good call. Let me do that right away.

**Pull request merged**
